<!--
 * Copyright © MageForge - Free Modules. All rights reserved.
 * Developed by : MageForge - Free Modules
 * Contact : max.developperfb@gmail.com
-->
<div id="reindex-product-modal" style="display:none;">
    <h2>Select Indexes to Reindex</h2>
    <form id="reindex-form">
        <div id="reindex-checkboxes"></div>
        <br>
        <button id="submit-reindex" class="action-primary">Reindex</button>
    </form>
</div>
